### ISSUE TITLE
default languages

### ISSUE THREAD

**Issue by breck7** [breck7/jtree#150]
- should we have the jtree cli?
- if so, we should install default langs: https://github.com/treenotation/treebase/issues/4

**Comment by SRS-WRKS** [comment]
A really nice feature of jtree is the ability work with users tools, instead of providing users tools to use, by default. 

I think it should have both.

**Comment by breck7** [comment]
Good feedback @SRS-WRKS ! I deleted the concept of registered grammars. Users can do that kind of thing themselves.
