### ISSUE TITLE
Parsers for treenotation

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/jtree#153]
As per clarification,

treenotation is syntax where there is no parent child relationships.

XML files have parsers, SGML files have them too. How do people write parsers for treebase if there are no relationships between parent node and child node.

Note: There are no discussions enabled for this project, so i posted this as an issue. Please forgive if its the wrong place to post such queries.

**Comment by SRS-WRKS** [comment]
I am sorry i got confused between leafDB and treeDB.

**Comment by breck7** [comment]
>  I am sorry i got confused between leafDB and treeDB.

Lol. Thank you! I can't believe how confusing I made things by having TreeBase and then TreeDB. Hopefully leafdb.org has clarified things. I apologize! Thanks for bringing that to my attention.
