### ISSUE TITLE
HOWTO : Duplicate keys value validation and their dependent keys

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/jtree#155]
check the number of keys of the same name in a table and have some validation logic (If some table entry has 2 websites then 2 usernames should be provided)

Can i check if certain keys have different values or same values ( mentioning the same website twice should be an error,etc ) 

As far as i am aware i have not found any information about how to manage accidental additions (https://prettier.io/) might help a lot in detecting this manually.

**Comment by breck7** [comment]
> Can i check if certain keys have different values or same values ( mentioning the same website twice should be an error,etc )

Great idea! We should add this to Grammar.

**Comment by SRS-WRKS** [comment]
@breck7 adding support for https://github.com/prettier/prettier and then having minimal diff patches seems to be important for working with own tools. Your code reviews have caught this many times, It would be really nice for people like me, if you could have something more simpler than grammar to solve this issue 

Context: https://github.com/breck7/pldb/commit/cca4f51c5264de4cbf0fa5c28814ce6d1249a130#r86588860

**Comment by breck7** [comment]
This is a great idea @SRS-WRKS !! Lets do it. I can look into it as well if you have other things

**Comment by celtic-coder** [comment]
These are good suggestions! 👍

**Comment by SRS-WRKS** [comment]
@celtic-coder : thank you

@breck7 : We can get this done. I just hope i had found you sooner !!!! , Please bear with me in the short term.

**Comment by breck7** [comment]
Added the ability to check for duplicates: 1bceda9a
