### ISSUE TITLE
information loss during conversion of treeformat and its domain specific languages

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/jtree#158]
As far as i am aware pldb (https://github.com/breck7/pldb) format can be converted into scroll but there dont seem to be any information about building hierarchical tree formats for various uses and its interoperability.

The lack of information about interoperability between various treeDB various dialects for domain specific languages need to be documented somewhere.

**Comment by SRS-WRKS** [comment]
Related information https://github.com/breck7/pldb/issues/223 

Should all dialects/DSL  of tree notation support REPL environment and CLI tools ??

**Comment by breck7** [comment]
> The lack of information about interoperability between various treeDB various dialects for domain specific languages need to be documented somewhere.

This is a good point! Tree Notation is extremely basic and to convert and DSL like PLDB to/from something like JSON or XML requires the PLDB Grammar. And that is the case for *all* tree languages. This should be better documented.
