### ISSUE TITLE
jtree designer feature requests

### ISSUE THREAD

**Issue by ghost** [breck7/jtree#159]
Jtree designer is really nice,

But should it include support for loading files from my disk too ??

Also the ability to load grammar and my "own values" files ( like in pldb, load the pldb.grammer file  [https://pldb.com/pldb.grammar] and a single file under database/things/ sub folder [https://github.com/breck7/pldb/tree/main/database/things] ) would be really nice.

**Comment by SRS-WRKS** [comment]
Related: https://github.com/breck7/jtree/issues/153 , parsers could be included too

**Comment by breck7** [comment]
This is in now.

For example:

https://jtree.treenotation.org/designer#url%20https%3A%2F%2Fpldb.io%2Fpldb.grammar%0AprogramUrl%20https%3A%2F%2Fpldb.io%2Fconcepts%2Fphp.scroll
