### ISSUE TITLE
Feature : multi value keys

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/jtree#166]
There are two approaches to multi value keys. 

One is to have an array. The other is to declare the same key multiple times. 

Each has its own advantages and disadvantages, especially for verifying data integrity in data, de-duplication of data and data verification all of which are crucial steps before visualizing data using ohayo (https://github.com/breck7/ohayo) to conduct data science.

Would tree notation plan to support both, in the long run ??

**Comment by breck7** [comment]
Yes we will always support both.

The simple one liner is generally preferred, but allowing 2 keys allows you to do more complex things when needed. Here is a hypothetical example:

In year 1 things might be simple:
```
country United States and India
```

In year 3 you might want to provide more detailed information:
```
country United States
 notes The language was first started in the USA.
 start 2001
 end 2003
country India
 notes After 2 years, development was moved to India.
 start 2003
 end present
```

But we should have better support for the first kind of lists. https://github.com/breck7/jtree/issues/167
