### ISSUE TITLE
jtree support for content filtering and sandboxing

### ISSUE THREAD

**Issue by ghost** [breck7/jtree#171]
Should jtree support content filtering like Noscript (https://en.wikipedia.org/wiki/NoScript) or uBlock origin (https://en.wikipedia.org/wiki/UBlock_Origin) 

or sandboxing like seccomp bpf (https://en.wikipedia.org/wiki/Seccomp)

To encourage people to share DSL scripts with less worry about security ?  People could be worried about script writers talking advantage of steep learning curve required to learn a new DSL in an interpreter that is currently in early development.

**Comment by breck7** [comment]
Cross origin should protect against these in browser. When running Scroll scripts locally using "scroll build", this is an issue that we could do a better job on
