### ISSUE TITLE
Testing Foreign keys and Urlnodes in jtree/treeDB

### ISSUE THREAD

**Issue by ghost** [breck7/jtree#172]
Note: Post edited for clarity:

Is there a way to more thoroughly test foreign keys and urnodes in jtree ?

I cant seem to find a link on treeDB and foreign keys here (I am sorry) so referring to foreign keys in trenotation is a bit hard, for normal users.
For urlnodes:
Url error code detection would be nice.
Link rot protection tests based on Wikipedia's  policy on URL link rot (https://en.wikipedia.org/wiki/Wikipedia:Link_rot)
detect typos in URL for example using

-  Many modern browsers now support phishing/XSS attacks prevention plugins, 
- HTTPS certificate checking for URL Nodes could also be leveraged to an extent for the same purpose.
- Optional check for return MIME type of url nodes responses

**Comment by breck7** [comment]
https://github.com/breck7/scroll/issues/113
